// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\FPGA_TEST\FPGA.v
// Created: 2026-07-28 00:30:25
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0
// Target subsystem base rate: inf
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FPGA
// Source Path: FPGA_TEST/FPGA
// Hierarchy Level: 0
// Model version: 1.4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FPGA
          (tdata_0,
           tdata_1,
           tdata_2,
           tdata_3,
           tdata_4,
           tdata_5,
           tdata_6,
           tdata_7,
           tdata_8,
           tdata_9,
           tdata_10,
           tdata_11,
           tdata_12,
           tdata_13,
           tdata_14,
           tdata_15,
           tdata_16,
           tdata_17,
           tdata_18,
           tdata_19,
           tdata_20,
           tdata_21,
           tdata_22,
           tdata_23,
           tdata_24,
           tvalid_valid,
           tvalid_tlast,
           StreamEnable,
           tready_ready,
           computeDone,
           Outport_0,
           Outport_1,
           Outport_2,
           Outport_3,
           Outport_4,
           Outport_5,
           Outport_6,
           Outport_7,
           Outport_8,
           Outport1_0,
           Outport1_1,
           Outport1_2,
           Outport1_3,
           Outport1_4,
           Outport1_5,
           Outport1_6,
           Outport1_7,
           Outport1_8,
           Outport1_9,
           Outport1_10,
           Outport1_11,
           Outport1_12,
           Outport1_13,
           Outport1_14,
           Outport1_15);


  input   [63:0] tdata_0;  // double
  input   [63:0] tdata_1;  // double
  input   [63:0] tdata_2;  // double
  input   [63:0] tdata_3;  // double
  input   [63:0] tdata_4;  // double
  input   [63:0] tdata_5;  // double
  input   [63:0] tdata_6;  // double
  input   [63:0] tdata_7;  // double
  input   [63:0] tdata_8;  // double
  input   [63:0] tdata_9;  // double
  input   [63:0] tdata_10;  // double
  input   [63:0] tdata_11;  // double
  input   [63:0] tdata_12;  // double
  input   [63:0] tdata_13;  // double
  input   [63:0] tdata_14;  // double
  input   [63:0] tdata_15;  // double
  input   [63:0] tdata_16;  // double
  input   [63:0] tdata_17;  // double
  input   [63:0] tdata_18;  // double
  input   [63:0] tdata_19;  // double
  input   [63:0] tdata_20;  // double
  input   [63:0] tdata_21;  // double
  input   [63:0] tdata_22;  // double
  input   [63:0] tdata_23;  // double
  input   [63:0] tdata_24;  // double
  input   tvalid_valid;
  input   tvalid_tlast;
  input   StreamEnable;
  output  tready_ready;
  output  computeDone;
  output  [63:0] Outport_0;  // double
  output  [63:0] Outport_1;  // double
  output  [63:0] Outport_2;  // double
  output  [63:0] Outport_3;  // double
  output  [63:0] Outport_4;  // double
  output  [63:0] Outport_5;  // double
  output  [63:0] Outport_6;  // double
  output  [63:0] Outport_7;  // double
  output  [63:0] Outport_8;  // double
  output  [63:0] Outport1_0;  // double
  output  [63:0] Outport1_1;  // double
  output  [63:0] Outport1_2;  // double
  output  [63:0] Outport1_3;  // double
  output  [63:0] Outport1_4;  // double
  output  [63:0] Outport1_5;  // double
  output  [63:0] Outport1_6;  // double
  output  [63:0] Outport1_7;  // double
  output  [63:0] Outport1_8;  // double
  output  [63:0] Outport1_9;  // double
  output  [63:0] Outport1_10;  // double
  output  [63:0] Outport1_11;  // double
  output  [63:0] Outport1_12;  // double
  output  [63:0] Outport1_13;  // double
  output  [63:0] Outport1_14;  // double
  output  [63:0] Outport1_15;  // double


  wire SoC_Bus_Creator_out1_ready;
  wire [63:0] matA_0;  // ufix64
  wire [63:0] matA_1;  // ufix64
  wire [63:0] matA_2;  // ufix64
  wire [63:0] matA_3;  // ufix64
  wire [63:0] matA_4;  // ufix64
  wire [63:0] matA_5;  // ufix64
  wire [63:0] matA_6;  // ufix64
  wire [63:0] matA_7;  // ufix64
  wire [63:0] matA_8;  // ufix64
  wire [63:0] matB_0;  // ufix64
  wire [63:0] matB_1;  // ufix64
  wire [63:0] matB_2;  // ufix64
  wire [63:0] matB_3;  // ufix64
  wire [63:0] matB_4;  // ufix64
  wire [63:0] matB_5;  // ufix64
  wire [63:0] matB_6;  // ufix64
  wire [63:0] matB_7;  // ufix64
  wire [63:0] matB_8;  // ufix64
  wire [63:0] matB_9;  // ufix64
  wire [63:0] matB_10;  // ufix64
  wire [63:0] matB_11;  // ufix64
  wire [63:0] matB_12;  // ufix64
  wire [63:0] matB_13;  // ufix64
  wire [63:0] matB_14;  // ufix64
  wire [63:0] matB_15;  // ufix64


  SoC_Bus_Creator u_SoC_Bus_Creator (.ready(StreamEnable),
                                     .ctrlBus_ready(SoC_Bus_Creator_out1_ready)
                                     );

  assign tready_ready = SoC_Bus_Creator_out1_ready;

  assign computeDone = StreamEnable;

  MATLAB_Function u_MATLAB_Function (.U_0(tdata_0),  // double
                                     .U_1(tdata_1),  // double
                                     .U_2(tdata_2),  // double
                                     .U_3(tdata_3),  // double
                                     .U_4(tdata_4),  // double
                                     .U_5(tdata_5),  // double
                                     .U_6(tdata_6),  // double
                                     .U_7(tdata_7),  // double
                                     .U_8(tdata_8),  // double
                                     .U_9(tdata_9),  // double
                                     .U_10(tdata_10),  // double
                                     .U_11(tdata_11),  // double
                                     .U_12(tdata_12),  // double
                                     .U_13(tdata_13),  // double
                                     .U_14(tdata_14),  // double
                                     .U_15(tdata_15),  // double
                                     .U_16(tdata_16),  // double
                                     .U_17(tdata_17),  // double
                                     .U_18(tdata_18),  // double
                                     .U_19(tdata_19),  // double
                                     .U_20(tdata_20),  // double
                                     .U_21(tdata_21),  // double
                                     .U_22(tdata_22),  // double
                                     .U_23(tdata_23),  // double
                                     .U_24(tdata_24),  // double
                                     .matA_0(matA_0),  // double
                                     .matA_1(matA_1),  // double
                                     .matA_2(matA_2),  // double
                                     .matA_3(matA_3),  // double
                                     .matA_4(matA_4),  // double
                                     .matA_5(matA_5),  // double
                                     .matA_6(matA_6),  // double
                                     .matA_7(matA_7),  // double
                                     .matA_8(matA_8),  // double
                                     .matB_0(matB_0),  // double
                                     .matB_1(matB_1),  // double
                                     .matB_2(matB_2),  // double
                                     .matB_3(matB_3),  // double
                                     .matB_4(matB_4),  // double
                                     .matB_5(matB_5),  // double
                                     .matB_6(matB_6),  // double
                                     .matB_7(matB_7),  // double
                                     .matB_8(matB_8),  // double
                                     .matB_9(matB_9),  // double
                                     .matB_10(matB_10),  // double
                                     .matB_11(matB_11),  // double
                                     .matB_12(matB_12),  // double
                                     .matB_13(matB_13),  // double
                                     .matB_14(matB_14),  // double
                                     .matB_15(matB_15)  // double
                                     );

  assign Outport_0 = matA_0;

  assign Outport_1 = matA_1;

  assign Outport_2 = matA_2;

  assign Outport_3 = matA_3;

  assign Outport_4 = matA_4;

  assign Outport_5 = matA_5;

  assign Outport_6 = matA_6;

  assign Outport_7 = matA_7;

  assign Outport_8 = matA_8;

  assign Outport1_0 = matB_0;

  assign Outport1_1 = matB_1;

  assign Outport1_2 = matB_2;

  assign Outport1_3 = matB_3;

  assign Outport1_4 = matB_4;

  assign Outport1_5 = matB_5;

  assign Outport1_6 = matB_6;

  assign Outport1_7 = matB_7;

  assign Outport1_8 = matB_8;

  assign Outport1_9 = matB_9;

  assign Outport1_10 = matB_10;

  assign Outport1_11 = matB_11;

  assign Outport1_12 = matB_12;

  assign Outport1_13 = matB_13;

  assign Outport1_14 = matB_14;

  assign Outport1_15 = matB_15;

endmodule  // FPGA

