// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\FPGA_TEST\MATLAB_Function.v
// Created: 2026-07-28 00:30:25
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: MATLAB_Function
// Source Path: FPGA_TEST/FPGA/MATLAB Function
// Hierarchy Level: 1
// Model version: 1.4
// 
// U è 25x1 double
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module MATLAB_Function
          (U_0,
           U_1,
           U_2,
           U_3,
           U_4,
           U_5,
           U_6,
           U_7,
           U_8,
           U_9,
           U_10,
           U_11,
           U_12,
           U_13,
           U_14,
           U_15,
           U_16,
           U_17,
           U_18,
           U_19,
           U_20,
           U_21,
           U_22,
           U_23,
           U_24,
           matA_0,
           matA_1,
           matA_2,
           matA_3,
           matA_4,
           matA_5,
           matA_6,
           matA_7,
           matA_8,
           matB_0,
           matB_1,
           matB_2,
           matB_3,
           matB_4,
           matB_5,
           matB_6,
           matB_7,
           matB_8,
           matB_9,
           matB_10,
           matB_11,
           matB_12,
           matB_13,
           matB_14,
           matB_15);


  input   [63:0] U_0;  // double
  input   [63:0] U_1;  // double
  input   [63:0] U_2;  // double
  input   [63:0] U_3;  // double
  input   [63:0] U_4;  // double
  input   [63:0] U_5;  // double
  input   [63:0] U_6;  // double
  input   [63:0] U_7;  // double
  input   [63:0] U_8;  // double
  input   [63:0] U_9;  // double
  input   [63:0] U_10;  // double
  input   [63:0] U_11;  // double
  input   [63:0] U_12;  // double
  input   [63:0] U_13;  // double
  input   [63:0] U_14;  // double
  input   [63:0] U_15;  // double
  input   [63:0] U_16;  // double
  input   [63:0] U_17;  // double
  input   [63:0] U_18;  // double
  input   [63:0] U_19;  // double
  input   [63:0] U_20;  // double
  input   [63:0] U_21;  // double
  input   [63:0] U_22;  // double
  input   [63:0] U_23;  // double
  input   [63:0] U_24;  // double
  output  [63:0] matA_0;  // double
  output  [63:0] matA_1;  // double
  output  [63:0] matA_2;  // double
  output  [63:0] matA_3;  // double
  output  [63:0] matA_4;  // double
  output  [63:0] matA_5;  // double
  output  [63:0] matA_6;  // double
  output  [63:0] matA_7;  // double
  output  [63:0] matA_8;  // double
  output  [63:0] matB_0;  // double
  output  [63:0] matB_1;  // double
  output  [63:0] matB_2;  // double
  output  [63:0] matB_3;  // double
  output  [63:0] matB_4;  // double
  output  [63:0] matB_5;  // double
  output  [63:0] matB_6;  // double
  output  [63:0] matB_7;  // double
  output  [63:0] matB_8;  // double
  output  [63:0] matB_9;  // double
  output  [63:0] matB_10;  // double
  output  [63:0] matB_11;  // double
  output  [63:0] matB_12;  // double
  output  [63:0] matB_13;  // double
  output  [63:0] matB_14;  // double
  output  [63:0] matB_15;  // double


  wire [63:0] out0 [0:8];  // ufix64 [9]
  wire [63:0] matA [0:2] [0:2];  // ufix64 [3x3]
  wire [63:0] out0_1 [0:15];  // ufix64 [16]
  wire [63:0] matB [0:3] [0:3];  // ufix64 [4x4]


  assign out0[0] = U_0;
  assign out0[1] = U_1;
  assign out0[2] = U_2;
  assign out0[3] = U_3;
  assign out0[4] = U_4;
  assign out0[5] = U_5;
  assign out0[6] = U_6;
  assign out0[7] = U_7;
  assign out0[8] = U_8;

  generate
    genvar idx3;
    for(idx3 = 0; idx3 < 3; idx3 = idx3 + 1) begin : matA_gen1
      genvar idx2;
      for(idx2 = 0; idx2 < 3; idx2 = idx2 + 1) begin : matA_gen
        assign matA[idx2][idx3] = out0[idx2 + (idx3 * 3)];
      end
    end
  endgenerate

  assign matA_0 = matA[0][0];

  assign matA_1 = matA[1][0];

  assign matA_2 = matA[2][0];

  assign matA_3 = matA[0][1];

  assign matA_4 = matA[1][1];

  assign matA_5 = matA[2][1];

  assign matA_6 = matA[0][2];

  assign matA_7 = matA[1][2];

  assign matA_8 = matA[2][2];

  assign out0_1[0] = U_9;
  assign out0_1[1] = U_10;
  assign out0_1[2] = U_11;
  assign out0_1[3] = U_12;
  assign out0_1[4] = U_13;
  assign out0_1[5] = U_14;
  assign out0_1[6] = U_15;
  assign out0_1[7] = U_16;
  assign out0_1[8] = U_17;
  assign out0_1[9] = U_18;
  assign out0_1[10] = U_19;
  assign out0_1[11] = U_20;
  assign out0_1[12] = U_21;
  assign out0_1[13] = U_22;
  assign out0_1[14] = U_23;
  assign out0_1[15] = U_24;

  generate
    genvar idx1;
    for(idx1 = 0; idx1 < 4; idx1 = idx1 + 1) begin : matB_gen1
      genvar idx;
      for(idx = 0; idx < 4; idx = idx + 1) begin : matB_gen
        assign matB[idx][idx1] = out0_1[idx + (idx1 * 4)];
      end
    end
  endgenerate

  assign matB_0 = matB[0][0];

  assign matB_1 = matB[1][0];

  assign matB_2 = matB[2][0];

  assign matB_3 = matB[3][0];

  assign matB_4 = matB[0][1];

  assign matB_5 = matB[1][1];

  assign matB_6 = matB[2][1];

  assign matB_7 = matB[3][1];

  assign matB_8 = matB[0][2];

  assign matB_9 = matB[1][2];

  assign matB_10 = matB[2][2];

  assign matB_11 = matB[3][2];

  assign matB_12 = matB[0][3];

  assign matB_13 = matB[1][3];

  assign matB_14 = matB[2][3];

  assign matB_15 = matB[3][3];

endmodule  // MATLAB_Function

