// -------------------------------------------------------------
// 
// File Name: hdlsrc_fixedpoint_gen2\FPGA_Prova1_fixedpoint\FPGA_Prova1_fixedpoint.v
// Created: 2026-07-27 21:23:43
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1e-08
// Target subsystem base rate: 1e-08
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FPGA_Prova1_fixedpoint
// Source Path: FPGA_Prova1_fixedpoint
// Hierarchy Level: 0
// Model version: 1.7
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FPGA_Prova1_fixedpoint
          (tdata_0,
           tdata_1,
           tdata_2,
           tdata_3,
           tdata_4,
           tdata_5,
           tdata_6,
           tdata_7,
           tdata_8,
           tdata_9,
           tdata_10,
           tdata_11,
           tdata_12,
           tdata_13,
           tdata_14,
           tdata_15,
           tdata_16,
           tdata_17,
           tdata_18,
           tdata_19,
           tdata_20,
           tdata_21,
           tdata_22,
           tdata_23,
           tdata_24,
           tvalid_valid,
           tvalid_tlast,
           StreamEnable,
           tready_ready,
           computeDone,
           matA_out_0,
           matA_out_1,
           matA_out_2,
           matA_out_3,
           matA_out_4,
           matA_out_5,
           matA_out_6,
           matA_out_7,
           matA_out_8,
           matB_out_0,
           matB_out_1,
           matB_out_2,
           matB_out_3,
           matB_out_4,
           matB_out_5,
           matB_out_6,
           matB_out_7,
           matB_out_8,
           matB_out_9,
           matB_out_10,
           matB_out_11,
           matB_out_12,
           matB_out_13,
           matB_out_14,
           matB_out_15,
           matA_fixed_out_0,
           matA_fixed_out_1,
           matA_fixed_out_2,
           matA_fixed_out_3,
           matA_fixed_out_4,
           matA_fixed_out_5,
           matA_fixed_out_6,
           matA_fixed_out_7,
           matA_fixed_out_8);


  input   signed [31:0] tdata_0;  // sfix32_En16
  input   signed [31:0] tdata_1;  // sfix32_En16
  input   signed [31:0] tdata_2;  // sfix32_En16
  input   signed [31:0] tdata_3;  // sfix32_En16
  input   signed [31:0] tdata_4;  // sfix32_En16
  input   signed [31:0] tdata_5;  // sfix32_En16
  input   signed [31:0] tdata_6;  // sfix32_En16
  input   signed [31:0] tdata_7;  // sfix32_En16
  input   signed [31:0] tdata_8;  // sfix32_En16
  input   signed [31:0] tdata_9;  // sfix32_En16
  input   signed [31:0] tdata_10;  // sfix32_En16
  input   signed [31:0] tdata_11;  // sfix32_En16
  input   signed [31:0] tdata_12;  // sfix32_En16
  input   signed [31:0] tdata_13;  // sfix32_En16
  input   signed [31:0] tdata_14;  // sfix32_En16
  input   signed [31:0] tdata_15;  // sfix32_En16
  input   signed [31:0] tdata_16;  // sfix32_En16
  input   signed [31:0] tdata_17;  // sfix32_En16
  input   signed [31:0] tdata_18;  // sfix32_En16
  input   signed [31:0] tdata_19;  // sfix32_En16
  input   signed [31:0] tdata_20;  // sfix32_En16
  input   signed [31:0] tdata_21;  // sfix32_En16
  input   signed [31:0] tdata_22;  // sfix32_En16
  input   signed [31:0] tdata_23;  // sfix32_En16
  input   signed [31:0] tdata_24;  // sfix32_En16
  input   tvalid_valid;
  input   tvalid_tlast;
  input   StreamEnable;
  output  tready_ready;
  output  computeDone;
  output  signed [31:0] matA_out_0;  // sfix32_En16
  output  signed [31:0] matA_out_1;  // sfix32_En16
  output  signed [31:0] matA_out_2;  // sfix32_En16
  output  signed [31:0] matA_out_3;  // sfix32_En16
  output  signed [31:0] matA_out_4;  // sfix32_En16
  output  signed [31:0] matA_out_5;  // sfix32_En16
  output  signed [31:0] matA_out_6;  // sfix32_En16
  output  signed [31:0] matA_out_7;  // sfix32_En16
  output  signed [31:0] matA_out_8;  // sfix32_En16
  output  signed [31:0] matB_out_0;  // sfix32_En16
  output  signed [31:0] matB_out_1;  // sfix32_En16
  output  signed [31:0] matB_out_2;  // sfix32_En16
  output  signed [31:0] matB_out_3;  // sfix32_En16
  output  signed [31:0] matB_out_4;  // sfix32_En16
  output  signed [31:0] matB_out_5;  // sfix32_En16
  output  signed [31:0] matB_out_6;  // sfix32_En16
  output  signed [31:0] matB_out_7;  // sfix32_En16
  output  signed [31:0] matB_out_8;  // sfix32_En16
  output  signed [31:0] matB_out_9;  // sfix32_En16
  output  signed [31:0] matB_out_10;  // sfix32_En16
  output  signed [31:0] matB_out_11;  // sfix32_En16
  output  signed [31:0] matB_out_12;  // sfix32_En16
  output  signed [31:0] matB_out_13;  // sfix32_En16
  output  signed [31:0] matB_out_14;  // sfix32_En16
  output  signed [31:0] matB_out_15;  // sfix32_En16
  output  signed [15:0] matA_fixed_out_0;  // sfix16_En10
  output  signed [15:0] matA_fixed_out_1;  // sfix16_En10
  output  signed [15:0] matA_fixed_out_2;  // sfix16_En10
  output  signed [15:0] matA_fixed_out_3;  // sfix16_En10
  output  signed [15:0] matA_fixed_out_4;  // sfix16_En10
  output  signed [15:0] matA_fixed_out_5;  // sfix16_En10
  output  signed [15:0] matA_fixed_out_6;  // sfix16_En10
  output  signed [15:0] matA_fixed_out_7;  // sfix16_En10
  output  signed [15:0] matA_fixed_out_8;  // sfix16_En10


  wire SoC_Bus_Creator_out1_ready;
  wire signed [31:0] matA_0;  // sfix32_En16
  wire signed [31:0] matA_1;  // sfix32_En16
  wire signed [31:0] matA_2;  // sfix32_En16
  wire signed [31:0] matA_3;  // sfix32_En16
  wire signed [31:0] matA_4;  // sfix32_En16
  wire signed [31:0] matA_5;  // sfix32_En16
  wire signed [31:0] matA_6;  // sfix32_En16
  wire signed [31:0] matA_7;  // sfix32_En16
  wire signed [31:0] matA_8;  // sfix32_En16
  wire signed [31:0] matB_0;  // sfix32_En16
  wire signed [31:0] matB_1;  // sfix32_En16
  wire signed [31:0] matB_2;  // sfix32_En16
  wire signed [31:0] matB_3;  // sfix32_En16
  wire signed [31:0] matB_4;  // sfix32_En16
  wire signed [31:0] matB_5;  // sfix32_En16
  wire signed [31:0] matB_6;  // sfix32_En16
  wire signed [31:0] matB_7;  // sfix32_En16
  wire signed [31:0] matB_8;  // sfix32_En16
  wire signed [31:0] matB_9;  // sfix32_En16
  wire signed [31:0] matB_10;  // sfix32_En16
  wire signed [31:0] matB_11;  // sfix32_En16
  wire signed [31:0] matB_12;  // sfix32_En16
  wire signed [31:0] matB_13;  // sfix32_En16
  wire signed [31:0] matB_14;  // sfix32_En16
  wire signed [31:0] matB_15;  // sfix32_En16
  wire signed [31:0] matA [0:2] [0:2];  // sfix32_En16 [3x3]
  wire signed [31:0] c13_matA [0:8];  // sfix32_En16 [9]
  wire signed [15:0] c13_DTC_matA_out1 [0:8];  // sfix16_En10 [9]
  wire signed [31:0] Gain_matA_mul_temp;  // sfix32_En23
  wire signed [31:0] Gain_matA_mul_temp_1;  // sfix32_En23
  wire signed [31:0] Gain_matA_mul_temp_2;  // sfix32_En23
  wire signed [31:0] Gain_matA_mul_temp_3;  // sfix32_En23
  wire signed [31:0] Gain_matA_mul_temp_4;  // sfix32_En23
  wire signed [31:0] Gain_matA_mul_temp_5;  // sfix32_En23
  wire signed [31:0] Gain_matA_mul_temp_6;  // sfix32_En23
  wire signed [31:0] Gain_matA_mul_temp_7;  // sfix32_En23
  wire signed [31:0] Gain_matA_mul_temp_8;  // sfix32_En23
  wire signed [15:0] c8_Gain_matA_out1 [0:8];  // sfix16_En10 [9]
  wire signed [15:0] Gain_matA_out1 [0:2] [0:2];  // sfix16_En10 [3x3]


  SoC_Bus_Creator u_SoC_Bus_Creator (.ready(StreamEnable),
                                     .ctrlBus_ready(SoC_Bus_Creator_out1_ready)
                                     );

  assign tready_ready = SoC_Bus_Creator_out1_ready;

  assign computeDone = StreamEnable;

  MATLAB_Function u_MATLAB_Function (.U_0(tdata_0),  // sfix32_En16
                                     .U_1(tdata_1),  // sfix32_En16
                                     .U_2(tdata_2),  // sfix32_En16
                                     .U_3(tdata_3),  // sfix32_En16
                                     .U_4(tdata_4),  // sfix32_En16
                                     .U_5(tdata_5),  // sfix32_En16
                                     .U_6(tdata_6),  // sfix32_En16
                                     .U_7(tdata_7),  // sfix32_En16
                                     .U_8(tdata_8),  // sfix32_En16
                                     .U_9(tdata_9),  // sfix32_En16
                                     .U_10(tdata_10),  // sfix32_En16
                                     .U_11(tdata_11),  // sfix32_En16
                                     .U_12(tdata_12),  // sfix32_En16
                                     .U_13(tdata_13),  // sfix32_En16
                                     .U_14(tdata_14),  // sfix32_En16
                                     .U_15(tdata_15),  // sfix32_En16
                                     .U_16(tdata_16),  // sfix32_En16
                                     .U_17(tdata_17),  // sfix32_En16
                                     .U_18(tdata_18),  // sfix32_En16
                                     .U_19(tdata_19),  // sfix32_En16
                                     .U_20(tdata_20),  // sfix32_En16
                                     .U_21(tdata_21),  // sfix32_En16
                                     .U_22(tdata_22),  // sfix32_En16
                                     .U_23(tdata_23),  // sfix32_En16
                                     .U_24(tdata_24),  // sfix32_En16
                                     .matA_0(matA_0),  // sfix32_En16
                                     .matA_1(matA_1),  // sfix32_En16
                                     .matA_2(matA_2),  // sfix32_En16
                                     .matA_3(matA_3),  // sfix32_En16
                                     .matA_4(matA_4),  // sfix32_En16
                                     .matA_5(matA_5),  // sfix32_En16
                                     .matA_6(matA_6),  // sfix32_En16
                                     .matA_7(matA_7),  // sfix32_En16
                                     .matA_8(matA_8),  // sfix32_En16
                                     .matB_0(matB_0),  // sfix32_En16
                                     .matB_1(matB_1),  // sfix32_En16
                                     .matB_2(matB_2),  // sfix32_En16
                                     .matB_3(matB_3),  // sfix32_En16
                                     .matB_4(matB_4),  // sfix32_En16
                                     .matB_5(matB_5),  // sfix32_En16
                                     .matB_6(matB_6),  // sfix32_En16
                                     .matB_7(matB_7),  // sfix32_En16
                                     .matB_8(matB_8),  // sfix32_En16
                                     .matB_9(matB_9),  // sfix32_En16
                                     .matB_10(matB_10),  // sfix32_En16
                                     .matB_11(matB_11),  // sfix32_En16
                                     .matB_12(matB_12),  // sfix32_En16
                                     .matB_13(matB_13),  // sfix32_En16
                                     .matB_14(matB_14),  // sfix32_En16
                                     .matB_15(matB_15)  // sfix32_En16
                                     );

  assign matA_out_0 = matA_0;

  assign matA_out_1 = matA_1;

  assign matA_out_2 = matA_2;

  assign matA_out_3 = matA_3;

  assign matA_out_4 = matA_4;

  assign matA_out_5 = matA_5;

  assign matA_out_6 = matA_6;

  assign matA_out_7 = matA_7;

  assign matA_out_8 = matA_8;

  assign matB_out_0 = matB_0;

  assign matB_out_1 = matB_1;

  assign matB_out_2 = matB_2;

  assign matB_out_3 = matB_3;

  assign matB_out_4 = matB_4;

  assign matB_out_5 = matB_5;

  assign matB_out_6 = matB_6;

  assign matB_out_7 = matB_7;

  assign matB_out_8 = matB_8;

  assign matB_out_9 = matB_9;

  assign matB_out_10 = matB_10;

  assign matB_out_11 = matB_11;

  assign matB_out_12 = matB_12;

  assign matB_out_13 = matB_13;

  assign matB_out_14 = matB_14;

  assign matB_out_15 = matB_15;

  assign matA[0][0] = matA_0;
  assign matA[1][0] = matA_1;
  assign matA[2][0] = matA_2;
  assign matA[0][1] = matA_3;
  assign matA[1][1] = matA_4;
  assign matA[2][1] = matA_5;
  assign matA[0][2] = matA_6;
  assign matA[1][2] = matA_7;
  assign matA[2][2] = matA_8;

  generate
    genvar idx3;
    for(idx3 = 0; idx3 < 3; idx3 = idx3 + 1) begin : c13_matA_gen1
      genvar idx2;
      for(idx2 = 0; idx2 < 3; idx2 = idx2 + 1) begin : c13_matA_gen
        assign c13_matA[idx2 + (idx3 * 3)] = matA[idx2][idx3];
      end
    end
  endgenerate


  genvar ii1;
  generate
    for(ii1 = 32'sd0; ii1 <= 32'sd8; ii1 = ii1 + 32'sd1) begin:c13_DTC_matA_out1_gen
      assign c13_DTC_matA_out1[ii1] = c13_matA[ii1][21:6];
    end
  endgenerate




  assign Gain_matA_mul_temp = 16'sb0111011001100110 * c13_DTC_matA_out1[0];
  assign c8_Gain_matA_out1[0] = Gain_matA_mul_temp[28:13];
  assign Gain_matA_mul_temp_1 = 16'sb0111011001100110 * c13_DTC_matA_out1[1];
  assign c8_Gain_matA_out1[1] = Gain_matA_mul_temp_1[28:13];
  assign Gain_matA_mul_temp_2 = 16'sb0111011001100110 * c13_DTC_matA_out1[2];
  assign c8_Gain_matA_out1[2] = Gain_matA_mul_temp_2[28:13];
  assign Gain_matA_mul_temp_3 = 16'sb0111011001100110 * c13_DTC_matA_out1[3];
  assign c8_Gain_matA_out1[3] = Gain_matA_mul_temp_3[28:13];
  assign Gain_matA_mul_temp_4 = 16'sb0111011001100110 * c13_DTC_matA_out1[4];
  assign c8_Gain_matA_out1[4] = Gain_matA_mul_temp_4[28:13];
  assign Gain_matA_mul_temp_5 = 16'sb0111011001100110 * c13_DTC_matA_out1[5];
  assign c8_Gain_matA_out1[5] = Gain_matA_mul_temp_5[28:13];
  assign Gain_matA_mul_temp_6 = 16'sb0111011001100110 * c13_DTC_matA_out1[6];
  assign c8_Gain_matA_out1[6] = Gain_matA_mul_temp_6[28:13];
  assign Gain_matA_mul_temp_7 = 16'sb0111011001100110 * c13_DTC_matA_out1[7];
  assign c8_Gain_matA_out1[7] = Gain_matA_mul_temp_7[28:13];
  assign Gain_matA_mul_temp_8 = 16'sb0111011001100110 * c13_DTC_matA_out1[8];
  assign c8_Gain_matA_out1[8] = Gain_matA_mul_temp_8[28:13];



  generate
    genvar idx1;
    for(idx1 = 0; idx1 < 3; idx1 = idx1 + 1) begin : Gain_matA_out1_gen1
      genvar idx;
      for(idx = 0; idx < 3; idx = idx + 1) begin : Gain_matA_out1_gen
        assign Gain_matA_out1[idx][idx1] = c8_Gain_matA_out1[idx + (idx1 * 3)];
      end
    end
  endgenerate

  assign matA_fixed_out_0 = Gain_matA_out1[0][0];

  assign matA_fixed_out_1 = Gain_matA_out1[1][0];

  assign matA_fixed_out_2 = Gain_matA_out1[2][0];

  assign matA_fixed_out_3 = Gain_matA_out1[0][1];

  assign matA_fixed_out_4 = Gain_matA_out1[1][1];

  assign matA_fixed_out_5 = Gain_matA_out1[2][1];

  assign matA_fixed_out_6 = Gain_matA_out1[0][2];

  assign matA_fixed_out_7 = Gain_matA_out1[1][2];

  assign matA_fixed_out_8 = Gain_matA_out1[2][2];

endmodule  // FPGA_Prova1_fixedpoint

