// -------------------------------------------------------------
// 
// File Name: hdlsrc_fixedpoint_gen2\FPGA_Prova1_fixedpoint\SoC_Bus_Creator.v
// Created: 2026-07-27 21:23:43
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SoC_Bus_Creator
// Source Path: FPGA_Prova1_fixedpoint/SoC Bus Creator
// Hierarchy Level: 1
// Model version: 1.7
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SoC_Bus_Creator
          (ready,
           ctrlBus_ready);


  input   ready;
  output  ctrlBus_ready;




  assign ctrlBus_ready = ready;

endmodule  // SoC_Bus_Creator

