// -------------------------------------------------------------
// 
// File Name: hdlsrc_generated_v3\FPGA_Prova1\FPGA_Prova1.v
// Created: 2026-07-27 16:50:08
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1e-08
// Target subsystem base rate: 1e-08
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FPGA_Prova1
// Source Path: FPGA_Prova1
// Hierarchy Level: 0
// Model version: 1.4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FPGA_Prova1
          (tdata_0,
           tdata_1,
           tdata_2,
           tdata_3,
           tdata_4,
           tdata_5,
           tdata_6,
           tdata_7,
           tdata_8,
           tdata_9,
           tdata_10,
           tdata_11,
           tdata_12,
           tdata_13,
           tdata_14,
           tdata_15,
           tdata_16,
           tdata_17,
           tdata_18,
           tdata_19,
           tdata_20,
           tdata_21,
           tdata_22,
           tdata_23,
           tdata_24,
           tvalid_valid,
           tvalid_tlast,
           StreamEnable,
           tready_ready,
           computeDone,
           matA_out_0,
           matA_out_1,
           matA_out_2,
           matA_out_3,
           matA_out_4,
           matA_out_5,
           matA_out_6,
           matA_out_7,
           matA_out_8,
           matB_out_0,
           matB_out_1,
           matB_out_2,
           matB_out_3,
           matB_out_4,
           matB_out_5,
           matB_out_6,
           matB_out_7,
           matB_out_8,
           matB_out_9,
           matB_out_10,
           matB_out_11,
           matB_out_12,
           matB_out_13,
           matB_out_14,
           matB_out_15);


  input   [63:0] tdata_0;  // ufix64
  input   [63:0] tdata_1;  // ufix64
  input   [63:0] tdata_2;  // ufix64
  input   [63:0] tdata_3;  // ufix64
  input   [63:0] tdata_4;  // ufix64
  input   [63:0] tdata_5;  // ufix64
  input   [63:0] tdata_6;  // ufix64
  input   [63:0] tdata_7;  // ufix64
  input   [63:0] tdata_8;  // ufix64
  input   [63:0] tdata_9;  // ufix64
  input   [63:0] tdata_10;  // ufix64
  input   [63:0] tdata_11;  // ufix64
  input   [63:0] tdata_12;  // ufix64
  input   [63:0] tdata_13;  // ufix64
  input   [63:0] tdata_14;  // ufix64
  input   [63:0] tdata_15;  // ufix64
  input   [63:0] tdata_16;  // ufix64
  input   [63:0] tdata_17;  // ufix64
  input   [63:0] tdata_18;  // ufix64
  input   [63:0] tdata_19;  // ufix64
  input   [63:0] tdata_20;  // ufix64
  input   [63:0] tdata_21;  // ufix64
  input   [63:0] tdata_22;  // ufix64
  input   [63:0] tdata_23;  // ufix64
  input   [63:0] tdata_24;  // ufix64
  input   tvalid_valid;
  input   tvalid_tlast;
  input   StreamEnable;
  output  tready_ready;
  output  computeDone;
  output  [63:0] matA_out_0;  // ufix64
  output  [63:0] matA_out_1;  // ufix64
  output  [63:0] matA_out_2;  // ufix64
  output  [63:0] matA_out_3;  // ufix64
  output  [63:0] matA_out_4;  // ufix64
  output  [63:0] matA_out_5;  // ufix64
  output  [63:0] matA_out_6;  // ufix64
  output  [63:0] matA_out_7;  // ufix64
  output  [63:0] matA_out_8;  // ufix64
  output  [63:0] matB_out_0;  // ufix64
  output  [63:0] matB_out_1;  // ufix64
  output  [63:0] matB_out_2;  // ufix64
  output  [63:0] matB_out_3;  // ufix64
  output  [63:0] matB_out_4;  // ufix64
  output  [63:0] matB_out_5;  // ufix64
  output  [63:0] matB_out_6;  // ufix64
  output  [63:0] matB_out_7;  // ufix64
  output  [63:0] matB_out_8;  // ufix64
  output  [63:0] matB_out_9;  // ufix64
  output  [63:0] matB_out_10;  // ufix64
  output  [63:0] matB_out_11;  // ufix64
  output  [63:0] matB_out_12;  // ufix64
  output  [63:0] matB_out_13;  // ufix64
  output  [63:0] matB_out_14;  // ufix64
  output  [63:0] matB_out_15;  // ufix64


  wire SoC_Bus_Creator_out1_ready;
  wire [63:0] matA_0;  // ufix64
  wire [63:0] matA_1;  // ufix64
  wire [63:0] matA_2;  // ufix64
  wire [63:0] matA_3;  // ufix64
  wire [63:0] matA_4;  // ufix64
  wire [63:0] matA_5;  // ufix64
  wire [63:0] matA_6;  // ufix64
  wire [63:0] matA_7;  // ufix64
  wire [63:0] matA_8;  // ufix64
  wire [63:0] matB_0;  // ufix64
  wire [63:0] matB_1;  // ufix64
  wire [63:0] matB_2;  // ufix64
  wire [63:0] matB_3;  // ufix64
  wire [63:0] matB_4;  // ufix64
  wire [63:0] matB_5;  // ufix64
  wire [63:0] matB_6;  // ufix64
  wire [63:0] matB_7;  // ufix64
  wire [63:0] matB_8;  // ufix64
  wire [63:0] matB_9;  // ufix64
  wire [63:0] matB_10;  // ufix64
  wire [63:0] matB_11;  // ufix64
  wire [63:0] matB_12;  // ufix64
  wire [63:0] matB_13;  // ufix64
  wire [63:0] matB_14;  // ufix64
  wire [63:0] matB_15;  // ufix64


  SoC_Bus_Creator u_SoC_Bus_Creator (.ready(StreamEnable),
                                     .ctrlBus_ready(SoC_Bus_Creator_out1_ready)
                                     );

  assign tready_ready = SoC_Bus_Creator_out1_ready;

  assign computeDone = StreamEnable;

  MATLAB_Function u_MATLAB_Function (.U_0(tdata_0),  // ufix64
                                     .U_1(tdata_1),  // ufix64
                                     .U_2(tdata_2),  // ufix64
                                     .U_3(tdata_3),  // ufix64
                                     .U_4(tdata_4),  // ufix64
                                     .U_5(tdata_5),  // ufix64
                                     .U_6(tdata_6),  // ufix64
                                     .U_7(tdata_7),  // ufix64
                                     .U_8(tdata_8),  // ufix64
                                     .U_9(tdata_9),  // ufix64
                                     .U_10(tdata_10),  // ufix64
                                     .U_11(tdata_11),  // ufix64
                                     .U_12(tdata_12),  // ufix64
                                     .U_13(tdata_13),  // ufix64
                                     .U_14(tdata_14),  // ufix64
                                     .U_15(tdata_15),  // ufix64
                                     .U_16(tdata_16),  // ufix64
                                     .U_17(tdata_17),  // ufix64
                                     .U_18(tdata_18),  // ufix64
                                     .U_19(tdata_19),  // ufix64
                                     .U_20(tdata_20),  // ufix64
                                     .U_21(tdata_21),  // ufix64
                                     .U_22(tdata_22),  // ufix64
                                     .U_23(tdata_23),  // ufix64
                                     .U_24(tdata_24),  // ufix64
                                     .matA_0(matA_0),  // ufix64
                                     .matA_1(matA_1),  // ufix64
                                     .matA_2(matA_2),  // ufix64
                                     .matA_3(matA_3),  // ufix64
                                     .matA_4(matA_4),  // ufix64
                                     .matA_5(matA_5),  // ufix64
                                     .matA_6(matA_6),  // ufix64
                                     .matA_7(matA_7),  // ufix64
                                     .matA_8(matA_8),  // ufix64
                                     .matB_0(matB_0),  // ufix64
                                     .matB_1(matB_1),  // ufix64
                                     .matB_2(matB_2),  // ufix64
                                     .matB_3(matB_3),  // ufix64
                                     .matB_4(matB_4),  // ufix64
                                     .matB_5(matB_5),  // ufix64
                                     .matB_6(matB_6),  // ufix64
                                     .matB_7(matB_7),  // ufix64
                                     .matB_8(matB_8),  // ufix64
                                     .matB_9(matB_9),  // ufix64
                                     .matB_10(matB_10),  // ufix64
                                     .matB_11(matB_11),  // ufix64
                                     .matB_12(matB_12),  // ufix64
                                     .matB_13(matB_13),  // ufix64
                                     .matB_14(matB_14),  // ufix64
                                     .matB_15(matB_15)  // ufix64
                                     );

  assign matA_out_0 = matA_0;

  assign matA_out_1 = matA_1;

  assign matA_out_2 = matA_2;

  assign matA_out_3 = matA_3;

  assign matA_out_4 = matA_4;

  assign matA_out_5 = matA_5;

  assign matA_out_6 = matA_6;

  assign matA_out_7 = matA_7;

  assign matA_out_8 = matA_8;

  assign matB_out_0 = matB_0;

  assign matB_out_1 = matB_1;

  assign matB_out_2 = matB_2;

  assign matB_out_3 = matB_3;

  assign matB_out_4 = matB_4;

  assign matB_out_5 = matB_5;

  assign matB_out_6 = matB_6;

  assign matB_out_7 = matB_7;

  assign matB_out_8 = matB_8;

  assign matB_out_9 = matB_9;

  assign matB_out_10 = matB_10;

  assign matB_out_11 = matB_11;

  assign matB_out_12 = matB_12;

  assign matB_out_13 = matB_13;

  assign matB_out_14 = matB_14;

  assign matB_out_15 = matB_15;

endmodule  // FPGA_Prova1

