// -------------------------------------------------------------
// 
// File Name: hdlsrc_generated_v3\FPGA_Prova1\MATLAB_Function.v
// Created: 2026-07-27 16:50:08
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: MATLAB_Function
// Source Path: FPGA_Prova1/MATLAB Function
// Hierarchy Level: 1
// Model version: 1.4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module MATLAB_Function
          (U_0,
           U_1,
           U_2,
           U_3,
           U_4,
           U_5,
           U_6,
           U_7,
           U_8,
           U_9,
           U_10,
           U_11,
           U_12,
           U_13,
           U_14,
           U_15,
           U_16,
           U_17,
           U_18,
           U_19,
           U_20,
           U_21,
           U_22,
           U_23,
           U_24,
           matA_0,
           matA_1,
           matA_2,
           matA_3,
           matA_4,
           matA_5,
           matA_6,
           matA_7,
           matA_8,
           matB_0,
           matB_1,
           matB_2,
           matB_3,
           matB_4,
           matB_5,
           matB_6,
           matB_7,
           matB_8,
           matB_9,
           matB_10,
           matB_11,
           matB_12,
           matB_13,
           matB_14,
           matB_15);


  input   [63:0] U_0;  // ufix64
  input   [63:0] U_1;  // ufix64
  input   [63:0] U_2;  // ufix64
  input   [63:0] U_3;  // ufix64
  input   [63:0] U_4;  // ufix64
  input   [63:0] U_5;  // ufix64
  input   [63:0] U_6;  // ufix64
  input   [63:0] U_7;  // ufix64
  input   [63:0] U_8;  // ufix64
  input   [63:0] U_9;  // ufix64
  input   [63:0] U_10;  // ufix64
  input   [63:0] U_11;  // ufix64
  input   [63:0] U_12;  // ufix64
  input   [63:0] U_13;  // ufix64
  input   [63:0] U_14;  // ufix64
  input   [63:0] U_15;  // ufix64
  input   [63:0] U_16;  // ufix64
  input   [63:0] U_17;  // ufix64
  input   [63:0] U_18;  // ufix64
  input   [63:0] U_19;  // ufix64
  input   [63:0] U_20;  // ufix64
  input   [63:0] U_21;  // ufix64
  input   [63:0] U_22;  // ufix64
  input   [63:0] U_23;  // ufix64
  input   [63:0] U_24;  // ufix64
  output  [63:0] matA_0;  // ufix64
  output  [63:0] matA_1;  // ufix64
  output  [63:0] matA_2;  // ufix64
  output  [63:0] matA_3;  // ufix64
  output  [63:0] matA_4;  // ufix64
  output  [63:0] matA_5;  // ufix64
  output  [63:0] matA_6;  // ufix64
  output  [63:0] matA_7;  // ufix64
  output  [63:0] matA_8;  // ufix64
  output  [63:0] matB_0;  // ufix64
  output  [63:0] matB_1;  // ufix64
  output  [63:0] matB_2;  // ufix64
  output  [63:0] matB_3;  // ufix64
  output  [63:0] matB_4;  // ufix64
  output  [63:0] matB_5;  // ufix64
  output  [63:0] matB_6;  // ufix64
  output  [63:0] matB_7;  // ufix64
  output  [63:0] matB_8;  // ufix64
  output  [63:0] matB_9;  // ufix64
  output  [63:0] matB_10;  // ufix64
  output  [63:0] matB_11;  // ufix64
  output  [63:0] matB_12;  // ufix64
  output  [63:0] matB_13;  // ufix64
  output  [63:0] matB_14;  // ufix64
  output  [63:0] matB_15;  // ufix64


  wire [63:0] U [0:24];  // ufix64 [25]
  reg [63:0] matA [0:2] [0:2];  // ufix64 [3x3]
  reg [63:0] matB [0:3] [0:3];  // ufix64 [4x4]
  reg signed [31:0] i;  // int32
  reg signed [31:0] i2;  // int32
  reg [7:0] cast_temp;  // ufix8
  reg [15:0] cast_temp_0;  // ufix16
  reg [15:0] mul_temp;  // ufix16
  reg signed [31:0] flat_idx;  // int32
  reg signed [31:0] i_0;  // int32
  reg signed [31:0] i2_0;  // int32
  reg [7:0] cast_temp_1;  // ufix8
  reg [15:0] cast_temp_2;  // ufix16
  reg [15:0] mul_temp_0;  // ufix16
  reg signed [31:0] flat_idx_0;  // int32


  assign U[0] = U_0;
  assign U[1] = U_1;
  assign U[2] = U_2;
  assign U[3] = U_3;
  assign U[4] = U_4;
  assign U[5] = U_5;
  assign U[6] = U_6;
  assign U[7] = U_7;
  assign U[8] = U_8;
  assign U[9] = U_9;
  assign U[10] = U_10;
  assign U[11] = U_11;
  assign U[12] = U_12;
  assign U[13] = U_13;
  assign U[14] = U_14;
  assign U[15] = U_15;
  assign U[16] = U_16;
  assign U[17] = U_17;
  assign U[18] = U_18;
  assign U[19] = U_19;
  assign U[20] = U_20;
  assign U[21] = U_21;
  assign U[22] = U_22;
  assign U[23] = U_23;
  assign U[24] = U_24;

  always @* begin
    cast_temp = 8'b00000000;
    cast_temp_0 = 16'b0000000000000000;
    mul_temp = 16'b0000000000000000;
    flat_idx = 32'sd0;
    cast_temp_1 = 8'b00000000;
    cast_temp_2 = 16'b0000000000000000;
    mul_temp_0 = 16'b0000000000000000;
    flat_idx_0 = 32'sd0;
    // U è 25x1 double

    for(i = 32'sd0; i <= 32'sd2; i = i + 32'sd1) begin
      for(i2 = 32'sd0; i2 <= 32'sd2; i2 = i2 + 32'sd1) begin
        cast_temp = i;
        cast_temp_0 = i2;
        mul_temp = cast_temp * 8'b00000011;
        flat_idx = mul_temp + cast_temp_0;
        matA[i2][i] = U[flat_idx];
      end
    end


    for(i_0 = 32'sd0; i_0 <= 32'sd3; i_0 = i_0 + 32'sd1) begin
      for(i2_0 = 32'sd0; i2_0 <= 32'sd3; i2_0 = i2_0 + 32'sd1) begin
        cast_temp_1 = i_0;
        cast_temp_2 = i2_0;
        mul_temp_0 = cast_temp_1 * 8'b00000100;
        flat_idx_0 = mul_temp_0 + cast_temp_2;
        matB[i2_0][i_0] = U[flat_idx_0];
      end
    end

  end



  assign matA_0 = matA[0][0];

  assign matA_1 = matA[1][0];

  assign matA_2 = matA[2][0];

  assign matA_3 = matA[0][1];

  assign matA_4 = matA[1][1];

  assign matA_5 = matA[2][1];

  assign matA_6 = matA[0][2];

  assign matA_7 = matA[1][2];

  assign matA_8 = matA[2][2];

  assign matB_0 = matB[0][0];

  assign matB_1 = matB[1][0];

  assign matB_2 = matB[2][0];

  assign matB_3 = matB[3][0];

  assign matB_4 = matB[0][1];

  assign matB_5 = matB[1][1];

  assign matB_6 = matB[2][1];

  assign matB_7 = matB[3][1];

  assign matB_8 = matB[0][2];

  assign matB_9 = matB[1][2];

  assign matB_10 = matB[2][2];

  assign matB_11 = matB[3][2];

  assign matB_12 = matB[0][3];

  assign matB_13 = matB[1][3];

  assign matB_14 = matB[2][3];

  assign matB_15 = matB[3][3];

endmodule  // MATLAB_Function

