// -------------------------------------------------------------
// 
// File Name: hdlsrc_generated_v3\FPGA_Prova1\SoC_Bus_Creator.v
// Created: 2026-07-27 16:50:08
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SoC_Bus_Creator
// Source Path: FPGA_Prova1/SoC Bus Creator
// Hierarchy Level: 1
// Model version: 1.4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SoC_Bus_Creator
          (ready,
           ctrlBus_ready);


  input   ready;
  output  ctrlBus_ready;




  assign ctrlBus_ready = ready;

endmodule  // SoC_Bus_Creator

