-- -------------------------------------------------------------
-- 
-- File Name: D:\SocBuilderBuild\prova2_vivado_prj\hdlsrc\soc_wrapper_fpga\soc_wrapp_ip_src_soc_wrapper_fpga.vhd
-- Created: 2026-07-31 12:34:52
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- done                          ce_out        1
-- busy                          ce_out        1
-- timeout_flag                  ce_out        1
-- cycles                        ce_out        1
-- u0                            ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: soc_wrapp_ip_src_soc_wrapper_fpga
-- Source Path: soc_wrapper_fpga
-- Hierarchy Level: 0
-- Model version: 1.1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.soc_wrapp_ip_src_soc_wrapper_fpga_pkg.ALL;

ENTITY soc_wrapp_ip_src_soc_wrapper_fpga IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        start_cmd                         :   IN    std_logic;
        timeout_thr                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        x0                                :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        x1                                :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        x2                                :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        x3                                :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        x4                                :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        x5                                :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        ce_out                            :   OUT   std_logic;
        done                              :   OUT   std_logic;
        busy                              :   OUT   std_logic;
        timeout_flag                      :   OUT   std_logic;
        cycles                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        u0                                :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
        );
END soc_wrapp_ip_src_soc_wrapper_fpga;


ARCHITECTURE rtl OF soc_wrapp_ip_src_soc_wrapper_fpga IS

  -- Component Declarations
  COMPONENT soc_wrapp_ip_src_compute_stub
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          x                               :   IN    vector_of_std_logic_vector32(0 TO 5);  -- sfix32_En16 [6]
          start_i                         :   IN    std_logic;
          done_o                          :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT soc_wrapp_ip_src_wrapper_fsm
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          start_cmd                       :   IN    std_logic;
          done_i                          :   IN    std_logic;
          timeout_thr                     :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          start_o                         :   OUT   std_logic;
          done_o                          :   OUT   std_logic;
          busy_o                          :   OUT   std_logic;
          timeout_o                       :   OUT   std_logic;
          cycles_o                        :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : soc_wrapp_ip_src_compute_stub
    USE ENTITY work.soc_wrapp_ip_src_compute_stub(rtl);

  FOR ALL : soc_wrapp_ip_src_wrapper_fsm
    USE ENTITY work.soc_wrapp_ip_src_wrapper_fsm(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL Mux_x_out1                       : vector_of_std_logic_vector32(0 TO 5);  -- ufix32 [6]
  SIGNAL start_o                          : std_logic;
  SIGNAL done_o                           : std_logic;
  SIGNAL done_o_1                         : std_logic;
  SIGNAL busy_o                           : std_logic;
  SIGNAL timeout_o                        : std_logic;
  SIGNAL cycles_o                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL x0_signed                        : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL u_latch_out1                     : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL u_hold_out1                      : signed(31 DOWNTO 0);  -- sfix32_En16

BEGIN
  u_compute_stub : soc_wrapp_ip_src_compute_stub
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              x => Mux_x_out1,  -- sfix32_En16 [6]
              start_i => start_o,
              done_o => done_o
              );

  u_wrapper_fsm : soc_wrapp_ip_src_wrapper_fsm
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              start_cmd => start_cmd,
              done_i => done_o,
              timeout_thr => timeout_thr,  -- uint32
              start_o => start_o,
              done_o => done_o_1,
              busy_o => busy_o,
              timeout_o => timeout_o,
              cycles_o => cycles_o  -- uint32
              );

  Mux_x_out1(0) <= x0;
  Mux_x_out1(1) <= x1;
  Mux_x_out1(2) <= x2;
  Mux_x_out1(3) <= x3;
  Mux_x_out1(4) <= x4;
  Mux_x_out1(5) <= x5;

  enb <= clk_enable;

  x0_signed <= signed(x0);

  u_hold_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      u_hold_out1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        u_hold_out1 <= u_latch_out1;
      END IF;
    END IF;
  END PROCESS u_hold_process;


  
  u_latch_out1 <= u_hold_out1 WHEN done_o_1 = '0' ELSE
      x0_signed;

  u0 <= std_logic_vector(u_latch_out1);

  ce_out <= clk_enable;

  done <= done_o_1;

  busy <= busy_o;

  timeout_flag <= timeout_o;

  cycles <= cycles_o;

END rtl;

