-- -------------------------------------------------------------
-- 
-- File Name: D:\SocBuilderBuild\prova2_vivado_prj\hdlsrc\soc_wrapper_fpga\soc_wrapp_ip_dut.vhd
-- Created: 2026-07-31 12:35:01
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: soc_wrapp_ip_dut
-- Source Path: soc_wrapp_ip/soc_wrapp_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY soc_wrapp_ip_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        start_cmd                         :   IN    std_logic;  -- ufix1
        timeout_thr                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        x0                                :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        x1                                :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        x2                                :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        x3                                :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        x4                                :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        x5                                :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        ce_out                            :   OUT   std_logic;  -- ufix1
        done                              :   OUT   std_logic;  -- ufix1
        busy                              :   OUT   std_logic;  -- ufix1
        timeout_flag                      :   OUT   std_logic;  -- ufix1
        cycles                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        u0                                :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
        );
END soc_wrapp_ip_dut;


ARCHITECTURE rtl OF soc_wrapp_ip_dut IS

  -- Component Declarations
  COMPONENT soc_wrapp_ip_src_soc_wrapper_fpga
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          start_cmd                       :   IN    std_logic;  -- ufix1
          timeout_thr                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          x0                              :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          x1                              :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          x2                              :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          x3                              :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          x4                              :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          x5                              :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          ce_out                          :   OUT   std_logic;  -- ufix1
          done                            :   OUT   std_logic;  -- ufix1
          busy                            :   OUT   std_logic;  -- ufix1
          timeout_flag                    :   OUT   std_logic;  -- ufix1
          cycles                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          u0                              :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : soc_wrapp_ip_src_soc_wrapper_fpga
    USE ENTITY work.soc_wrapp_ip_src_soc_wrapper_fpga(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL start_cmd_sig                    : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL done_sig                         : std_logic;  -- ufix1
  SIGNAL busy_sig                         : std_logic;  -- ufix1
  SIGNAL timeout_flag_sig                 : std_logic;  -- ufix1
  SIGNAL cycles_sig                       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL u0_sig                           : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_soc_wrapp_ip_src_soc_wrapper_fpga : soc_wrapp_ip_src_soc_wrapper_fpga
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              start_cmd => start_cmd_sig,  -- ufix1
              timeout_thr => timeout_thr,  -- ufix32
              x0 => x0,  -- sfix32_En16
              x1 => x1,  -- sfix32_En16
              x2 => x2,  -- sfix32_En16
              x3 => x3,  -- sfix32_En16
              x4 => x4,  -- sfix32_En16
              x5 => x5,  -- sfix32_En16
              ce_out => ce_out_sig,  -- ufix1
              done => done_sig,  -- ufix1
              busy => busy_sig,  -- ufix1
              timeout_flag => timeout_flag_sig,  -- ufix1
              cycles => cycles_sig,  -- ufix32
              u0 => u0_sig  -- sfix32_En16
              );

  start_cmd_sig <= start_cmd;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  done <= done_sig;

  busy <= busy_sig;

  timeout_flag <= timeout_flag_sig;

  cycles <= cycles_sig;

  u0 <= u0_sig;

END rtl;

