-- -------------------------------------------------------------
-- 
-- File Name: D:\SocBuilderBuild\prova2_vivado_prj\hdlsrc\soc_wrapper_fpga\soc_wrapp_ip.vhd
-- Created: 2026-07-31 12:35:01
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: -1
-- Target subsystem base rate: -1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: soc_wrapp_ip
-- Source Path: soc_wrapp_ip
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY soc_wrapp_ip IS
  PORT( IPCORE_CLK                        :   IN    std_logic;  -- ufix1
        IPCORE_RESETN                     :   IN    std_logic;  -- ufix1
        AXI4_Lite_ACLK                    :   IN    std_logic;  -- ufix1
        AXI4_Lite_ARESETN                 :   IN    std_logic;  -- ufix1
        AXI4_Lite_AWADDR                  :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        AXI4_Lite_AWVALID                 :   IN    std_logic;  -- ufix1
        AXI4_Lite_WDATA                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_Lite_WSTRB                   :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        AXI4_Lite_WVALID                  :   IN    std_logic;  -- ufix1
        AXI4_Lite_BREADY                  :   IN    std_logic;  -- ufix1
        AXI4_Lite_ARADDR                  :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        AXI4_Lite_ARVALID                 :   IN    std_logic;  -- ufix1
        AXI4_Lite_RREADY                  :   IN    std_logic;  -- ufix1
        AXI4_Lite_AWREADY                 :   OUT   std_logic;  -- ufix1
        AXI4_Lite_WREADY                  :   OUT   std_logic;  -- ufix1
        AXI4_Lite_BRESP                   :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI4_Lite_BVALID                  :   OUT   std_logic;  -- ufix1
        AXI4_Lite_ARREADY                 :   OUT   std_logic;  -- ufix1
        AXI4_Lite_RDATA                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_Lite_RRESP                   :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI4_Lite_RVALID                  :   OUT   std_logic  -- ufix1
        );
END soc_wrapp_ip;


ARCHITECTURE rtl OF soc_wrapp_ip IS

  -- Component Declarations
  COMPONENT soc_wrapp_ip_reset_sync
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset_in                        :   IN    std_logic;  -- ufix1
          reset_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT soc_wrapp_ip_dut
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset                           :   IN    std_logic;
          dut_enable                      :   IN    std_logic;  -- ufix1
          start_cmd                       :   IN    std_logic;  -- ufix1
          timeout_thr                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          x0                              :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          x1                              :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          x2                              :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          x3                              :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          x4                              :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          x5                              :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          ce_out                          :   OUT   std_logic;  -- ufix1
          done                            :   OUT   std_logic;  -- ufix1
          busy                            :   OUT   std_logic;  -- ufix1
          timeout_flag                    :   OUT   std_logic;  -- ufix1
          cycles                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          u0                              :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
          );
  END COMPONENT;

  COMPONENT soc_wrapp_ip_axi_lite
    PORT( reset                           :   IN    std_logic;
          AXI4_Lite_ACLK                  :   IN    std_logic;  -- ufix1
          AXI4_Lite_ARESETN               :   IN    std_logic;  -- ufix1
          AXI4_Lite_AWADDR                :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          AXI4_Lite_AWVALID               :   IN    std_logic;  -- ufix1
          AXI4_Lite_WDATA                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI4_Lite_WSTRB                 :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          AXI4_Lite_WVALID                :   IN    std_logic;  -- ufix1
          AXI4_Lite_BREADY                :   IN    std_logic;  -- ufix1
          AXI4_Lite_ARADDR                :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          AXI4_Lite_ARVALID               :   IN    std_logic;  -- ufix1
          AXI4_Lite_RREADY                :   IN    std_logic;  -- ufix1
          read_ip_timestamp               :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          read_done                       :   IN    std_logic;  -- ufix1
          read_busy                       :   IN    std_logic;  -- ufix1
          read_timeout_flag               :   IN    std_logic;  -- ufix1
          read_cycles                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          read_u0                         :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          AXI4_Lite_AWREADY               :   OUT   std_logic;  -- ufix1
          AXI4_Lite_WREADY                :   OUT   std_logic;  -- ufix1
          AXI4_Lite_BRESP                 :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          AXI4_Lite_BVALID                :   OUT   std_logic;  -- ufix1
          AXI4_Lite_ARREADY               :   OUT   std_logic;  -- ufix1
          AXI4_Lite_RDATA                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI4_Lite_RRESP                 :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          AXI4_Lite_RVALID                :   OUT   std_logic;  -- ufix1
          write_axi_enable                :   OUT   std_logic;  -- ufix1
          write_start_cmd                 :   OUT   std_logic;  -- ufix1
          write_timeout_thr               :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          write_x1                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          write_x2                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          write_x0                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          write_x3                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          write_x4                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          write_x5                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          reset_internal                  :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : soc_wrapp_ip_reset_sync
    USE ENTITY work.soc_wrapp_ip_reset_sync(rtl);

  FOR ALL : soc_wrapp_ip_dut
    USE ENTITY work.soc_wrapp_ip_dut(rtl);

  FOR ALL : soc_wrapp_ip_axi_lite
    USE ENTITY work.soc_wrapp_ip_axi_lite(rtl);

  -- Signals
  SIGNAL reset                            : std_logic;
  SIGNAL ip_timestamp                     : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reset_cm                         : std_logic;  -- ufix1
  SIGNAL reset_internal                   : std_logic;  -- ufix1
  SIGNAL reset_before_sync                : std_logic;  -- ufix1
  SIGNAL write_axi_enable                 : std_logic;  -- ufix1
  SIGNAL write_start_cmd                  : std_logic;  -- ufix1
  SIGNAL write_timeout_thr                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_x0                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_x1                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_x2                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_x3                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_x4                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL write_x5                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL done_sig                         : std_logic;  -- ufix1
  SIGNAL busy_sig                         : std_logic;  -- ufix1
  SIGNAL timeout_flag_sig                 : std_logic;  -- ufix1
  SIGNAL cycles_sig                       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL u0_sig                           : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL AXI4_Lite_BRESP_tmp              : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL AXI4_Lite_RDATA_tmp              : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL AXI4_Lite_RRESP_tmp              : std_logic_vector(1 DOWNTO 0);  -- ufix2

BEGIN
  u_soc_wrapp_ip_reset_sync_inst : soc_wrapp_ip_reset_sync
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset_in => reset_before_sync,  -- ufix1
              reset_out => reset
              );

  u_soc_wrapp_ip_dut_inst : soc_wrapp_ip_dut
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset => reset,
              dut_enable => write_axi_enable,  -- ufix1
              start_cmd => write_start_cmd,  -- ufix1
              timeout_thr => write_timeout_thr,  -- ufix32
              x0 => write_x0,  -- sfix32_En16
              x1 => write_x1,  -- sfix32_En16
              x2 => write_x2,  -- sfix32_En16
              x3 => write_x3,  -- sfix32_En16
              x4 => write_x4,  -- sfix32_En16
              x5 => write_x5,  -- sfix32_En16
              ce_out => ce_out_sig,  -- ufix1
              done => done_sig,  -- ufix1
              busy => busy_sig,  -- ufix1
              timeout_flag => timeout_flag_sig,  -- ufix1
              cycles => cycles_sig,  -- ufix32
              u0 => u0_sig  -- sfix32_En16
              );

  u_soc_wrapp_ip_axi_lite_inst : soc_wrapp_ip_axi_lite
    PORT MAP( reset => reset,
              AXI4_Lite_ACLK => AXI4_Lite_ACLK,  -- ufix1
              AXI4_Lite_ARESETN => AXI4_Lite_ARESETN,  -- ufix1
              AXI4_Lite_AWADDR => AXI4_Lite_AWADDR,  -- ufix16
              AXI4_Lite_AWVALID => AXI4_Lite_AWVALID,  -- ufix1
              AXI4_Lite_WDATA => AXI4_Lite_WDATA,  -- ufix32
              AXI4_Lite_WSTRB => AXI4_Lite_WSTRB,  -- ufix4
              AXI4_Lite_WVALID => AXI4_Lite_WVALID,  -- ufix1
              AXI4_Lite_BREADY => AXI4_Lite_BREADY,  -- ufix1
              AXI4_Lite_ARADDR => AXI4_Lite_ARADDR,  -- ufix16
              AXI4_Lite_ARVALID => AXI4_Lite_ARVALID,  -- ufix1
              AXI4_Lite_RREADY => AXI4_Lite_RREADY,  -- ufix1
              read_ip_timestamp => std_logic_vector(ip_timestamp),  -- ufix32
              read_done => done_sig,  -- ufix1
              read_busy => busy_sig,  -- ufix1
              read_timeout_flag => timeout_flag_sig,  -- ufix1
              read_cycles => cycles_sig,  -- ufix32
              read_u0 => u0_sig,  -- sfix32_En16
              AXI4_Lite_AWREADY => AXI4_Lite_AWREADY,  -- ufix1
              AXI4_Lite_WREADY => AXI4_Lite_WREADY,  -- ufix1
              AXI4_Lite_BRESP => AXI4_Lite_BRESP_tmp,  -- ufix2
              AXI4_Lite_BVALID => AXI4_Lite_BVALID,  -- ufix1
              AXI4_Lite_ARREADY => AXI4_Lite_ARREADY,  -- ufix1
              AXI4_Lite_RDATA => AXI4_Lite_RDATA_tmp,  -- ufix32
              AXI4_Lite_RRESP => AXI4_Lite_RRESP_tmp,  -- ufix2
              AXI4_Lite_RVALID => AXI4_Lite_RVALID,  -- ufix1
              write_axi_enable => write_axi_enable,  -- ufix1
              write_start_cmd => write_start_cmd,  -- ufix1
              write_timeout_thr => write_timeout_thr,  -- ufix32
              write_x1 => write_x1,  -- sfix32_En16
              write_x2 => write_x2,  -- sfix32_En16
              write_x0 => write_x0,  -- sfix32_En16
              write_x3 => write_x3,  -- sfix32_En16
              write_x4 => write_x4,  -- sfix32_En16
              write_x5 => write_x5,  -- sfix32_En16
              reset_internal => reset_internal  -- ufix1
              );

  ip_timestamp <= unsigned'(X"9B686982");

  reset_cm <=  NOT IPCORE_RESETN;

  reset_before_sync <= reset_cm OR reset_internal;

  AXI4_Lite_BRESP <= AXI4_Lite_BRESP_tmp;

  AXI4_Lite_RDATA <= AXI4_Lite_RDATA_tmp;

  AXI4_Lite_RRESP <= AXI4_Lite_RRESP_tmp;

END rtl;

