-- -------------------------------------------------------------
-- 
-- File Name: D:\SocBuilderBuild\prova2_vivado_prj\hdlsrc\soc_wrapper_fpga\soc_wrapp_ip_src_soc_wrapper_fpga_pkg.vhd
-- Created: 2026-07-31 12:34:52
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE soc_wrapp_ip_src_soc_wrapper_fpga_pkg IS
  TYPE vector_of_std_logic_vector32 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(31 DOWNTO 0);
  TYPE vector_of_signed32 IS ARRAY (NATURAL RANGE <>) OF signed(31 DOWNTO 0);
END soc_wrapp_ip_src_soc_wrapper_fpga_pkg;

