-- -------------------------------------------------------------
-- 
-- File Name: D:\SocBuilderBuild\prova2_vivado_prj\hdlsrc\soc_wrapper_fpga\soc_wrapp_ip_src_compute_stub.vhd
-- Created: 2026-07-31 12:34:52
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: soc_wrapp_ip_src_compute_stub
-- Source Path: soc_wrapper_fpga/compute_stub
-- Hierarchy Level: 1
-- Model version: 1.1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.soc_wrapp_ip_src_soc_wrapper_fpga_pkg.ALL;

ENTITY soc_wrapp_ip_src_compute_stub IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        x                                 :   IN    vector_of_std_logic_vector32(0 TO 5);  -- sfix32_En16 [6]
        start_i                           :   IN    std_logic;
        done_o                            :   OUT   std_logic
        );
END soc_wrapp_ip_src_compute_stub;


ARCHITECTURE rtl OF soc_wrapp_ip_src_compute_stub IS

  -- Signals
  SIGNAL x_signed                         : vector_of_signed32(0 TO 5);  -- sfix32_En16 [6]
  SIGNAL cnt                              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL running                          : std_logic;
  SIGNAL doneReg                          : std_logic;
  SIGNAL cnt_next                         : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL running_next                     : std_logic;
  SIGNAL doneReg_next                     : std_logic;

BEGIN
  outputgen: FOR k IN 0 TO 5 GENERATE
    x_signed(k) <= signed(x(k));
  END GENERATE;

  compute_stub_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      cnt <= to_unsigned(16#00000000#, 32);
      running <= '0';
      doneReg <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        cnt <= cnt_next;
        running <= running_next;
        doneReg <= doneReg_next;
      END IF;
    END IF;
  END PROCESS compute_stub_process;

  compute_stub_output : PROCESS (cnt, doneReg, running, start_i)
    VARIABLE cnt_temp : unsigned(31 DOWNTO 0);
    VARIABLE add_temp : unsigned(32 DOWNTO 0);
  BEGIN
    add_temp := to_unsigned(0, 33);
    cnt_temp := cnt;
    running_next <= running;
    -- GENERATO DA build_wrapper_fpga.m — non modificare a mano.
    --
    -- Segnaposto del blocco di calcolo di terzi. Latenza 500 cicli.
    -- NON e' un algoritmo: e' un ritardo con un handshake. Il calcolo
    -- vero e' di terzi e non e' nel nostro perimetro (docs/21_SPEC_WRAPPER §6).
    --
    -- Il blocco e' configurato NONDIRECT FEEDTHROUGH: e' cio' che rompe
    -- l'anello fsm -> stub -> fsm senza aggiungere ritardi a mano.
    -- In cambio vale una regola, prescritta dalla documentazione HDL Coder:
    --   "You must read the persistent variable's value BEFORE updating it."
    -- Le uscite si calcolano quindi in cima, dallo stato; gli aggiornamenti
    -- di stato stanno tutti dopo. Rompere questa regola non da' un errore:
    -- da' risultati sbagliati.
    --
    -- Il segnaposto NON produce il dato: solo done. Il percorso dati va al
    -- latch del wrapper direttamente da x (docs/21_SPEC_WRAPPER §3). Serve
    -- perche' col nondirect feedthrough NESSUNA uscita puo' dipendere da un
    -- ingresso, e "u = x(1:nu)" ne dipenderebbe.
    -- x resta fra gli ingressi per fedelta' al contratto: il blocco vero lo
    -- legge, e deve poterlo fare in qualunque momento fra start e done.
    -- --- USCITE: solo dallo stato, prima di ogni aggiornamento ---
    -- --- AGGIORNAMENTI DI STATO ---
    doneReg_next <= '0';
    IF running = '1' THEN 
      add_temp := resize(cnt, 33) + to_unsigned(1, 33);
      IF add_temp(32) /= '0' THEN 
        cnt_temp := X"FFFFFFFF";
      ELSE 
        cnt_temp := add_temp(31 DOWNTO 0);
      END IF;
      IF cnt_temp >= to_unsigned(16#000001F4#, 32) THEN 
        running_next <= '0';
        doneReg_next <= '1';
      END IF;
    ELSIF start_i = '1' THEN 
      running_next <= '1';
      cnt_temp := to_unsigned(16#00000000#, 32);
    END IF;
    done_o <= doneReg;
    cnt_next <= cnt_temp;
  END PROCESS compute_stub_output;


END rtl;

