-- -------------------------------------------------------------
-- 
-- File Name: D:\SocBuilderBuild\prova2_vivado_prj\hdlsrc\soc_wrapper_fpga\soc_wrapp_ip_src_wrapper_fsm.vhd
-- Created: 2026-07-31 12:34:52
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: soc_wrapp_ip_src_wrapper_fsm
-- Source Path: soc_wrapper_fpga/wrapper_fsm
-- Hierarchy Level: 1
-- Model version: 1.1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY soc_wrapp_ip_src_wrapper_fsm IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        start_cmd                         :   IN    std_logic;
        done_i                            :   IN    std_logic;
        timeout_thr                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        start_o                           :   OUT   std_logic;
        done_o                            :   OUT   std_logic;
        busy_o                            :   OUT   std_logic;
        timeout_o                         :   OUT   std_logic;
        cycles_o                          :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END soc_wrapp_ip_src_wrapper_fsm;


ARCHITECTURE rtl OF soc_wrapp_ip_src_wrapper_fsm IS

  -- Signals
  SIGNAL timeout_thr_unsigned             : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL cycles_o_tmp                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL state                            : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL cnt                              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL cyc                              : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL state_next                       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL cnt_next                         : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL cyc_next                         : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  timeout_thr_unsigned <= unsigned(timeout_thr);

  wrapper_fsm_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      state <= to_unsigned(16#00#, 8);
      cnt <= to_unsigned(16#00000000#, 32);
      cyc <= to_unsigned(16#00000000#, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        state <= state_next;
        cnt <= cnt_next;
        cyc <= cyc_next;
      END IF;
    END IF;
  END PROCESS wrapper_fsm_process;

  wrapper_fsm_output : PROCESS (cnt, cyc, done_i, start_cmd, state, timeout_thr_unsigned)
    VARIABLE state_temp : unsigned(7 DOWNTO 0);
    VARIABLE cnt_temp : unsigned(31 DOWNTO 0);
    VARIABLE cyc_temp : unsigned(31 DOWNTO 0);
    VARIABLE add_temp : unsigned(32 DOWNTO 0);
  BEGIN
    add_temp := to_unsigned(0, 33);
    state_temp := state;
    cnt_temp := cnt;
    cyc_temp := cyc;
    -- GENERATO DA build_wrapper_fpga.m — non modificare a mano.
    start_o <= '0';
    done_o <= '0';
    -- DONE e TIMEOUT sono impulsi di un ciclo
    timeout_o <= '0';
    IF state = to_unsigned(16#00000000#, 8) THEN 
      -- IDLE: si parte solo su comando. In RUNNING start_cmd e'
      -- ignorato: un solve alla volta (I4).
      IF start_cmd = '1' THEN 
        start_o <= '1';
        -- impulso di UN ciclo (I3)
        state_temp := to_unsigned(16#01#, 8);
        cnt_temp := to_unsigned(16#00000000#, 32);
      END IF;
    ELSE 
      add_temp := resize(cnt, 33) + to_unsigned(1, 33);
      IF add_temp(32) /= '0' THEN 
        cnt_temp := X"FFFFFFFF";
      ELSE 
        cnt_temp := add_temp(31 DOWNTO 0);
      END IF;
      IF done_i = '1' THEN 
        cyc_temp := cnt_temp;
        -- latenza misurata (I5)
        done_o <= '1';
        state_temp := to_unsigned(16#00#, 8);
      ELSIF cnt_temp >= timeout_thr_unsigned THEN 
        cyc_temp := cnt_temp;
        -- quanto si e' aspettato prima di mollare
        timeout_o <= '1';
        state_temp := to_unsigned(16#00#, 8);
        -- si esce SEMPRE (I6)
      END IF;
    END IF;
    IF state_temp = to_unsigned(16#00000001#, 8) THEN 
      busy_o <= '1';
    ELSE 
      busy_o <= '0';
    END IF;
    cycles_o_tmp <= cyc_temp;
    state_next <= state_temp;
    cnt_next <= cnt_temp;
    cyc_next <= cyc_temp;
  END PROCESS wrapper_fsm_output;


  cycles_o <= std_logic_vector(cycles_o_tmp);

END rtl;

