-- -------------------------------------------------------------
-- 
-- File Name: D:\SocBuilderBuild\prova2_vivado_prj\hdlsrc\soc_wrapper_fpga\soc_wrapp_ip_addr_decoder.vhd
-- Created: 2026-07-31 12:35:01
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: soc_wrapp_ip_addr_decoder
-- Source Path: soc_wrapp_ip/soc_wrapp_ip_axi_lite/soc_wrapp_ip_addr_decoder
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY soc_wrapp_ip_addr_decoder IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        data_write                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        addr_sel                          :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14
        wr_enb                            :   IN    std_logic;  -- ufix1
        rd_enb                            :   IN    std_logic;  -- ufix1
        read_ip_timestamp                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        read_done                         :   IN    std_logic;  -- ufix1
        read_busy                         :   IN    std_logic;  -- ufix1
        read_timeout_flag                 :   IN    std_logic;  -- ufix1
        read_cycles                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        read_u0                           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        data_read                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_axi_enable                  :   OUT   std_logic;  -- ufix1
        write_start_cmd                   :   OUT   std_logic;  -- ufix1
        write_timeout_thr                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_x1                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        write_x2                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        write_x0                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        write_x3                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        write_x4                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        write_x5                          :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
        );
END soc_wrapp_ip_addr_decoder;


ARCHITECTURE rtl OF soc_wrapp_ip_addr_decoder IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL addr_sel_unsigned                : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL decode_sel_ip_timestamp_1_1      : std_logic;  -- ufix1
  SIGNAL const_0                          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_ip_timestamp_unsigned       : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL const_1_1                        : std_logic;  -- ufix1
  SIGNAL decode_sel_cycles_1_1            : std_logic;  -- ufix1
  SIGNAL decode_sel_timeout_flag_1_1      : std_logic;  -- ufix1
  SIGNAL decode_sel_busy_1_1              : std_logic;  -- ufix1
  SIGNAL decode_sel_done_1_1              : std_logic;  -- ufix1
  SIGNAL read_reg_ip_timestamp            : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_ip_timestamp_1_1       : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_reg_done                    : std_logic;  -- ufix1
  SIGNAL data_slice_done_1                : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_done_1_1               : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_reg_busy                    : std_logic;  -- ufix1
  SIGNAL data_slice_busy_1                : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_busy_1_1               : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_reg_timeout_flag            : std_logic;  -- ufix1
  SIGNAL data_slice_timeout_flag_1        : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_timeout_flag_1_1       : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_cycles_unsigned             : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_u0_signed                   : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL decode_sel_u0_1_1                : std_logic;  -- ufix1
  SIGNAL read_reg_cycles                  : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_cycles_1_1             : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_reg_u0                      : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL data_slice_u0_1                  : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_u0_1_1                 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_sel_axi_enable_1_1        : std_logic;  -- ufix1
  SIGNAL reg_enb_axi_enable_1_1           : std_logic;  -- ufix1
  SIGNAL data_write_unsigned              : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL data_in_axi_enable               : std_logic;  -- ufix1
  SIGNAL data_reg_axi_enable_1_1          : std_logic;  -- ufix1
  SIGNAL decode_sel_start_cmd_1_1         : std_logic;  -- ufix1
  SIGNAL reg_enb_start_cmd_1_1            : std_logic;  -- ufix1
  SIGNAL data_in_start_cmd                : std_logic;  -- ufix1
  SIGNAL data_reg_start_cmd_1_1           : std_logic;  -- ufix1
  SIGNAL decode_sel_timeout_thr_1_1       : std_logic;  -- ufix1
  SIGNAL reg_enb_timeout_thr_1_1          : std_logic;  -- ufix1
  SIGNAL data_reg_timeout_thr_1_1         : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_sel_x1_1_1                : std_logic;  -- ufix1
  SIGNAL reg_enb_x1_1_1                   : std_logic;  -- ufix1
  SIGNAL data_in_x1                       : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL data_reg_x1_1_1                  : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL decode_sel_x2_1_1                : std_logic;  -- ufix1
  SIGNAL reg_enb_x2_1_1                   : std_logic;  -- ufix1
  SIGNAL data_in_x2                       : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL data_reg_x2_1_1                  : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL decode_sel_x0_1_1                : std_logic;  -- ufix1
  SIGNAL reg_enb_x0_1_1                   : std_logic;  -- ufix1
  SIGNAL data_in_x0                       : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL data_reg_x0_1_1                  : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL decode_sel_x3_1_1                : std_logic;  -- ufix1
  SIGNAL reg_enb_x3_1_1                   : std_logic;  -- ufix1
  SIGNAL data_in_x3                       : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL data_reg_x3_1_1                  : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL decode_sel_x4_1_1                : std_logic;  -- ufix1
  SIGNAL reg_enb_x4_1_1                   : std_logic;  -- ufix1
  SIGNAL data_in_x4                       : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL data_reg_x4_1_1                  : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL decode_sel_x5_1_1                : std_logic;  -- ufix1
  SIGNAL reg_enb_x5_1_1                   : std_logic;  -- ufix1
  SIGNAL data_in_x5                       : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL data_reg_x5_1_1                  : signed(31 DOWNTO 0);  -- sfix32_En16

BEGIN
  addr_sel_unsigned <= unsigned(addr_sel);

  
  decode_sel_ip_timestamp_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0002#, 14) ELSE
      '0';

  const_0 <= to_unsigned(0, 32);

  read_ip_timestamp_unsigned <= unsigned(read_ip_timestamp);

  const_1_1 <= '1';

  enb <= const_1_1;

  
  decode_sel_cycles_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#004B#, 14) ELSE
      '0';

  
  decode_sel_timeout_flag_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#004A#, 14) ELSE
      '0';

  
  decode_sel_busy_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0049#, 14) ELSE
      '0';

  
  decode_sel_done_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0048#, 14) ELSE
      '0';

  reg_ip_timestamp_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      read_reg_ip_timestamp <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        read_reg_ip_timestamp <= read_ip_timestamp_unsigned;
      END IF;
    END IF;
  END PROCESS reg_ip_timestamp_process;


  
  decode_rd_ip_timestamp_1_1 <= const_0 WHEN decode_sel_ip_timestamp_1_1 = '0' ELSE
      read_reg_ip_timestamp;

  reg_done_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      read_reg_done <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        read_reg_done <= read_done;
      END IF;
    END IF;
  END PROCESS reg_done_process;


  data_slice_done_1 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & read_reg_done;

  
  decode_rd_done_1_1 <= decode_rd_ip_timestamp_1_1 WHEN decode_sel_done_1_1 = '0' ELSE
      data_slice_done_1;

  reg_busy_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      read_reg_busy <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        read_reg_busy <= read_busy;
      END IF;
    END IF;
  END PROCESS reg_busy_process;


  data_slice_busy_1 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & read_reg_busy;

  
  decode_rd_busy_1_1 <= decode_rd_done_1_1 WHEN decode_sel_busy_1_1 = '0' ELSE
      data_slice_busy_1;

  reg_timeout_flag_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      read_reg_timeout_flag <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        read_reg_timeout_flag <= read_timeout_flag;
      END IF;
    END IF;
  END PROCESS reg_timeout_flag_process;


  data_slice_timeout_flag_1 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & read_reg_timeout_flag;

  
  decode_rd_timeout_flag_1_1 <= decode_rd_busy_1_1 WHEN decode_sel_timeout_flag_1_1 = '0' ELSE
      data_slice_timeout_flag_1;

  read_cycles_unsigned <= unsigned(read_cycles);

  read_u0_signed <= signed(read_u0);

  
  decode_sel_u0_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#004C#, 14) ELSE
      '0';

  reg_cycles_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      read_reg_cycles <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        read_reg_cycles <= read_cycles_unsigned;
      END IF;
    END IF;
  END PROCESS reg_cycles_process;


  
  decode_rd_cycles_1_1 <= decode_rd_timeout_flag_1_1 WHEN decode_sel_cycles_1_1 = '0' ELSE
      read_reg_cycles;

  reg_u0_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      read_reg_u0 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        read_reg_u0 <= read_u0_signed;
      END IF;
    END IF;
  END PROCESS reg_u0_process;


  data_slice_u0_1 <= unsigned(read_reg_u0);

  
  decode_rd_u0_1_1 <= decode_rd_cycles_1_1 WHEN decode_sel_u0_1_1 = '0' ELSE
      data_slice_u0_1;

  data_read <= std_logic_vector(decode_rd_u0_1_1);

  
  decode_sel_axi_enable_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0001#, 14) ELSE
      '0';

  reg_enb_axi_enable_1_1 <= decode_sel_axi_enable_1_1 AND wr_enb;

  data_write_unsigned <= unsigned(data_write);

  data_in_axi_enable <= data_write_unsigned(0);

  reg_axi_enable_1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_reg_axi_enable_1_1 <= '1';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_axi_enable_1_1 = '1' THEN
        data_reg_axi_enable_1_1 <= data_in_axi_enable;
      END IF;
    END IF;
  END PROCESS reg_axi_enable_1_1_process;


  
  decode_sel_start_cmd_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0040#, 14) ELSE
      '0';

  reg_enb_start_cmd_1_1 <= decode_sel_start_cmd_1_1 AND wr_enb;

  data_in_start_cmd <= data_write_unsigned(0);

  reg_start_cmd_1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_reg_start_cmd_1_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_start_cmd_1_1 = '1' THEN
        data_reg_start_cmd_1_1 <= data_in_start_cmd;
      END IF;
    END IF;
  END PROCESS reg_start_cmd_1_1_process;


  
  decode_sel_timeout_thr_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0041#, 14) ELSE
      '0';

  reg_enb_timeout_thr_1_1 <= decode_sel_timeout_thr_1_1 AND wr_enb;

  reg_timeout_thr_1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_reg_timeout_thr_1_1 <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_timeout_thr_1_1 = '1' THEN
        data_reg_timeout_thr_1_1 <= data_write_unsigned;
      END IF;
    END IF;
  END PROCESS reg_timeout_thr_1_1_process;


  write_timeout_thr <= std_logic_vector(data_reg_timeout_thr_1_1);

  
  decode_sel_x1_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0042#, 14) ELSE
      '0';

  reg_enb_x1_1_1 <= decode_sel_x1_1_1 AND wr_enb;

  data_in_x1 <= signed(data_write_unsigned);

  reg_x1_1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_reg_x1_1_1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_x1_1_1 = '1' THEN
        data_reg_x1_1_1 <= data_in_x1;
      END IF;
    END IF;
  END PROCESS reg_x1_1_1_process;


  write_x1 <= std_logic_vector(data_reg_x1_1_1);

  
  decode_sel_x2_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0043#, 14) ELSE
      '0';

  reg_enb_x2_1_1 <= decode_sel_x2_1_1 AND wr_enb;

  data_in_x2 <= signed(data_write_unsigned);

  reg_x2_1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_reg_x2_1_1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_x2_1_1 = '1' THEN
        data_reg_x2_1_1 <= data_in_x2;
      END IF;
    END IF;
  END PROCESS reg_x2_1_1_process;


  write_x2 <= std_logic_vector(data_reg_x2_1_1);

  
  decode_sel_x0_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0044#, 14) ELSE
      '0';

  reg_enb_x0_1_1 <= decode_sel_x0_1_1 AND wr_enb;

  data_in_x0 <= signed(data_write_unsigned);

  reg_x0_1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_reg_x0_1_1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_x0_1_1 = '1' THEN
        data_reg_x0_1_1 <= data_in_x0;
      END IF;
    END IF;
  END PROCESS reg_x0_1_1_process;


  write_x0 <= std_logic_vector(data_reg_x0_1_1);

  
  decode_sel_x3_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0045#, 14) ELSE
      '0';

  reg_enb_x3_1_1 <= decode_sel_x3_1_1 AND wr_enb;

  data_in_x3 <= signed(data_write_unsigned);

  reg_x3_1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_reg_x3_1_1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_x3_1_1 = '1' THEN
        data_reg_x3_1_1 <= data_in_x3;
      END IF;
    END IF;
  END PROCESS reg_x3_1_1_process;


  write_x3 <= std_logic_vector(data_reg_x3_1_1);

  
  decode_sel_x4_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0046#, 14) ELSE
      '0';

  reg_enb_x4_1_1 <= decode_sel_x4_1_1 AND wr_enb;

  data_in_x4 <= signed(data_write_unsigned);

  reg_x4_1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_reg_x4_1_1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_x4_1_1 = '1' THEN
        data_reg_x4_1_1 <= data_in_x4;
      END IF;
    END IF;
  END PROCESS reg_x4_1_1_process;


  write_x4 <= std_logic_vector(data_reg_x4_1_1);

  
  decode_sel_x5_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0047#, 14) ELSE
      '0';

  reg_enb_x5_1_1 <= decode_sel_x5_1_1 AND wr_enb;

  data_in_x5 <= signed(data_write_unsigned);

  reg_x5_1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_reg_x5_1_1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_x5_1_1 = '1' THEN
        data_reg_x5_1_1 <= data_in_x5;
      END IF;
    END IF;
  END PROCESS reg_x5_1_1_process;


  write_x5 <= std_logic_vector(data_reg_x5_1_1);

  write_axi_enable <= data_reg_axi_enable_1_1;

  write_start_cmd <= data_reg_start_cmd_1_1;

END rtl;

